FROM flink:1.17.2-scala_2.12-java11

# 0) Remove Flink's bundled Kafka connector + old clients
RUN rm -f /opt/flink/lib/flink-connector-kafka* \
          /opt/flink/lib/kafka-clients-*

# 1) GCP key
COPY gcp-key.json /opt/gcp/key.json
RUN chmod 400 /opt/gcp/key.json

# 2) Remove old S3/AWS jars
RUN rm -f /opt/flink/lib/hadoop-aws-*.jar \
           /opt/flink/lib/aws-java-sdk-*.jar \
           /opt/flink/lib/flink-s3-*.jar

# 3) GCS plugin
RUN mkdir -p /opt/flink/plugins/gcs
COPY jars/flink-gs-fs-hadoop-1.17.2.jar            /opt/flink/plugins/gcs/
COPY jars/gcs-connector-hadoop3-2.2.8-shaded.jar   /opt/flink/plugins/gcs/
COPY jars/google-api-services-storage-v1-rev20220705-1.32.1.jar /opt/flink/plugins/gcs/
COPY jars/hadoop-auth-3.3.1.jar                     /opt/flink/plugins/gcs/

# 4) Iceberg core + runtime + GCP
COPY jars/iceberg-core-1.8.1.jar                    /opt/flink/lib/
COPY jars/iceberg-flink-runtime-1.17-1.6.1.jar       /opt/flink/lib/
COPY jars/iceberg-gcp-1.8.1.jar                      /opt/flink/lib/

# 5) Your job + configs
COPY target/KafkaToIceberg.jar                       /opt/flink/usrlib/
COPY conf/core-site.xml                              /opt/flink/conf/core-site.xml
COPY conf/flink-conf.yaml                            /opt/flink/conf/flink-conf.yaml

# 7) Install the Flink SQL Kafka connector (1.17.2) + Kafka client 2.8.1
COPY jars/flink-sql-connector-kafka-1.17.2.jar /opt/flink/lib/
COPY jars/kafka-clients-2.8.1.jar           /opt/flink/lib/

# 7) Logging & tracing
COPY jars/commons-logging-1.2.jar                     /opt/flink/lib/
COPY jars/htrace-core4-4.2.0-incubating.jar           /opt/flink/lib/

# 8) Everything else
COPY jars/*.jar                                       /opt/flink/lib/
