services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    ports:
      - "9092:9092"
      - "29092:29092"

  jobmanager:
    container_name: jobmanager
    build:
      context: .            # where your Dockerfile lives
      dockerfile: Dockerfile
    image: flink-custom:1.17
    ports:
      - "8081:8081"
      - "6123:6123"
    volumes:
      - ./gcp-key.json:/opt/gcp/key.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/gcp/key.json
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    command: jobmanager

  taskmanager:
    container_name: taskmanager
    build:
      context: .
      dockerfile: Dockerfile
    image: flink-custom:1.17
    depends_on:
      - jobmanager
    volumes:
      - ./gcp-key.json:/opt/gcp/key.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/gcp/key.json
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
        taskmanager.memory.process.size: 1024m
    command: taskmanager