name: 'gamebot_project'
version: '1.0'
config-version: 2
profile: 'gamebot_iceberg_test'

model-paths: ["models"]
target-path: "target"

vars:
  iceberg_catalog: spark_catalog

models:
  gamebot_iceberg_test:
    +catalog: spark_catalog
    +materialized: view
    
